name: Check README Syntax
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Lint README.md
      run: markdownlint README.md
      continue-on-error: true 

    - name: Lint with custom markdownlint config
      run: markdownlint README.md --config .markdownlint.json
      continue-on-error: true 